# Generated by Django 5.0.6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('issue_date', models.CharField(blank=True, default='[Date / Year]', max_length=50)),
                ('credential_url', models.URLField(blank=True, default='https://[VERIFY_CREDENTIAL_URL]')),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('is_sample', models.BooleanField(default=False, help_text='Checked if this is an editable placeholder')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default="Bachelor's in Computer Science / Information Technology", max_length=150)),
                ('institution', models.CharField(default="St. Xavier's College, Kathmandu", max_length=150)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=100)),
                ('start_year', models.CharField(default='2022', max_length=10)),
                ('end_year', models.CharField(default='Present', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='Focusing on core computer science foundations, algorithms, object-oriented software engineering, database management systems, and applied machine learning.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='LearningTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-lightbulb', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Web', 'Web Development'), ('Python', 'Python Application'), ('Data', 'Data Science & Analysis'), ('AI', 'Artificial Intelligence & ML')], default='Web', max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies (e.g. Python, Django, PostgreSQL, Bootstrap 5)', max_length=255)),
                ('features', models.TextField(blank=True, help_text='Key features separated by new lines')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, default='https://github.com/[YOUR_GITHUB_USERNAME]/[PROJECT_REPO]', help_text='Editable GitHub repository link')),
                ('live_url', models.URLField(blank=True, help_text='Editable live demo link (leave empty if not deployed)')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rupesh Pathak', max_length=100)),
                ('title', models.CharField(default='Computer Science Student | Aspiring Software & AI Engineer', max_length=150)),
                ('short_bio', models.TextField(default="I'm a Computer Science student interested in software development, data science, and artificial intelligence. I enjoy turning ideas into practical software projects and continuously learning new technologies.")),
                ('about_full', models.TextField(blank=True, default="I am an undergraduate Computer Science student at St. Xavier's College, Kathmandu. My primary passions lie at the intersection of modern software engineering, web architectures, and applied artificial intelligence. I focus on writing clean, maintainable code, building robust backend systems, and exploring machine learning workflows to solve real-world problems.")),
                ('email', models.EmailField(default='[YOUR EMAIL]', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com/[YOUR_GITHUB_USERNAME]')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/[YOUR_LINKEDIN_USERNAME]')),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Data & AI', 'Data & AI'), ('Tools', 'Tools')], default='Programming', max_length=30)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Proficient', 'Proficient'), ('Advanced', 'Advanced')], default='Proficient', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon name (e.g. bi-filetype-py, bi-code-slash, bi-database)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
